namespace NSchema.Migration.Sql;

/// <summary>
/// Defines an interface for executing SQL plans generated by the schema migrator.
/// </summary>
public interface ISqlExecutor
{
    /// <summary>
    /// Executes the given SQL plan, applying the necessary changes to the database schema.
    /// </summary>
    /// <param name="plan">The SQL plan to execute, containing the ordered list of SQL commands to apply.</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests. If the operation is canceled, execution should stop gracefully.</param>
    /// <returns>A task that represents the asynchronous execution of the SQL plan. The task completes when all commands in the plan have been executed successfully.</returns>
    Task Execute(SqlPlan plan, CancellationToken cancellationToken = default);
}
